package lab8p2_haroldcamas;

import java.io.EOFException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harol
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() throws FileNotFoundException, IOException, ClassNotFoundException {
        initComponents();

        FileInputStream fo = null;
        ObjectInputStream os = null;

        File paisesA = new File("./PaisesParticipantes.UWU");
        File eventosA = new File("./Eventos.UWU");
        File nadadoresA = new File("./Nadadores.UWU");

        try {
            if (paisesA.exists()) {
                Pais temp = null;
                fo = new FileInputStream(paisesA);
                os = new ObjectInputStream(fo);

                try {
                    while ((temp = (Pais) os.readObject()) != null) {
                        paises.add(temp);
                    }
                } catch (EOFException e) {
                }
                fo.close();
                os.close();
            }
        } catch (Exception e) {
        }

        try {
            if (eventosA.exists()) {
                Evento temp = null;
                FileInputStream fo2 = new FileInputStream(eventosA);
                ObjectInputStream os2 = new ObjectInputStream(fo2);

                try {
                    while ((temp = (Evento) os2.readObject()) != null) {
                        eventos.add(temp);
                    }
                } catch (EOFException e) {
                }
                fo2.close();
                os2.close();
            }
        } catch (Exception e) {
        }

        try {
            if (nadadoresA.exists()) {
                Nadador temp = null;
                FileInputStream fo3 = new FileInputStream(nadadoresA);
                ObjectInputStream os3 = new ObjectInputStream(fo3);

                try {
                    while ((temp = (Nadador) os3.readObject()) != null) {
                        nadadores.add(temp);
                    }
                } catch (EOFException e) {
                }
                fo3.close();
                os3.close();
            }
        } catch (Exception e) {
        }

        cb_nacionalidad.setModel(refrescarModelo(paises, (DefaultComboBoxModel) cb_nacionalidad.getModel()));
        cb_listarNadadoresP.setModel(refrescarModelo(paises, (DefaultComboBoxModel) cb_listarNadadoresP.getModel()));
        cb_eventosSimulacion.setModel(refrescarModelo(eventos, (DefaultComboBoxModel) cb_eventosSimulacion.getModel()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_añadirPais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombrePais = new javax.swing.JTextField();
        sp_medallasPais = new javax.swing.JSpinner();
        bt_añadirPais = new javax.swing.JButton();
        jp_añadirEvento = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_estiloEvento = new javax.swing.JComboBox<>();
        cb_distanciaEvento = new javax.swing.JComboBox<>();
        sp_recordEvento = new javax.swing.JSpinner();
        bt_añadirEvento = new javax.swing.JButton();
        jp_añadirNadador = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_nombreNadador = new javax.swing.JTextField();
        cb_nacionalidad = new javax.swing.JComboBox<>();
        sp_edad = new javax.swing.JSpinner();
        sp_estatura = new javax.swing.JSpinner();
        cb_estiloNadador = new javax.swing.JComboBox<>();
        cb_distanciaNadador = new javax.swing.JComboBox<>();
        sp_recordNadador = new javax.swing.JSpinner();
        sp_medallasNadador = new javax.swing.JSpinner();
        bt_añadirNadador = new javax.swing.JButton();
        jp_listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_tablaNadadores = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        cb_listarNadadoresP = new javax.swing.JComboBox<>();
        bt_listarNadadores = new javax.swing.JButton();
        jp_listarEventos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_tablaEventos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        bt_refrescarEventos = new javax.swing.JButton();
        jp_simulacion = new javax.swing.JPanel();
        pg_piscina1 = new javax.swing.JProgressBar();
        pg_piscina2 = new javax.swing.JProgressBar();
        pg_piscina3 = new javax.swing.JProgressBar();
        cb_eventosSimulacion = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cb_nadadoresSimulacion = new javax.swing.JComboBox<>();
        bt_añadirNadadorS = new javax.swing.JButton();
        bt_empezarEvento = new javax.swing.JButton();
        bt_elegirEvento = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Medallas");

        sp_medallasPais.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        bt_añadirPais.setText("Añadir Pais");
        bt_añadirPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_añadirPaisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_añadirPaisLayout = new javax.swing.GroupLayout(jp_añadirPais);
        jp_añadirPais.setLayout(jp_añadirPaisLayout);
        jp_añadirPaisLayout.setHorizontalGroup(
            jp_añadirPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_añadirPaisLayout.createSequentialGroup()
                .addGroup(jp_añadirPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_añadirPaisLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jp_añadirPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(100, 100, 100)
                        .addGroup(jp_añadirPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombrePais, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(sp_medallasPais)))
                    .addGroup(jp_añadirPaisLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(bt_añadirPais, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jp_añadirPaisLayout.setVerticalGroup(
            jp_añadirPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_añadirPaisLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jp_añadirPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jp_añadirPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(sp_medallasPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(bt_añadirPais, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Pais", jp_añadirPais);

        jLabel3.setText("Estilo");

        jLabel4.setText("Distancia");

        jLabel5.setText("Tiempo Record (s)");

        cb_estiloEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa" }));

        cb_distanciaEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100m", "200m", "400m", "800m" }));

        sp_recordEvento.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.5d));

        bt_añadirEvento.setText("Añadir Evento");
        bt_añadirEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_añadirEventoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_añadirEventoLayout = new javax.swing.GroupLayout(jp_añadirEvento);
        jp_añadirEvento.setLayout(jp_añadirEventoLayout);
        jp_añadirEventoLayout.setHorizontalGroup(
            jp_añadirEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_añadirEventoLayout.createSequentialGroup()
                .addGroup(jp_añadirEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_añadirEventoLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jp_añadirEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(103, 103, 103)
                        .addGroup(jp_añadirEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_distanciaEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_estiloEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp_recordEvento)))
                    .addGroup(jp_añadirEventoLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(bt_añadirEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jp_añadirEventoLayout.setVerticalGroup(
            jp_añadirEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_añadirEventoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jp_añadirEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cb_estiloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jp_añadirEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cb_distanciaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jp_añadirEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(sp_recordEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(bt_añadirEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Evento", jp_añadirEvento);

        jLabel6.setText("Nombre");

        jLabel7.setText("Nacionalidad");

        jLabel8.setText("Edad");

        jLabel9.setText("Estatura");

        jLabel10.setText("Estilo");

        jLabel11.setText("Distancia");

        jLabel12.setText("Record");

        jLabel13.setText("Medallas");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));

        sp_estatura.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 3.0d, 0.1d));

        cb_estiloNadador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa" }));

        cb_distanciaNadador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100m", "200m", "400m", "800m" }));

        sp_recordNadador.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.1d, null, 0.5d));

        sp_medallasNadador.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        bt_añadirNadador.setText("Añadir Nadador");
        bt_añadirNadador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_añadirNadadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_añadirNadadorLayout = new javax.swing.GroupLayout(jp_añadirNadador);
        jp_añadirNadador.setLayout(jp_añadirNadadorLayout);
        jp_añadirNadadorLayout.setHorizontalGroup(
            jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_añadirNadadorLayout.createSequentialGroup()
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_añadirNadadorLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(138, 138, 138)
                        .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreNadador)
                            .addComponent(cb_nacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp_edad)
                            .addComponent(sp_estatura)
                            .addComponent(cb_estiloNadador, 0, 99, Short.MAX_VALUE)
                            .addComponent(cb_distanciaNadador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sp_recordNadador)
                            .addComponent(sp_medallasNadador)))
                    .addGroup(jp_añadirNadadorLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(bt_añadirNadador, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jp_añadirNadadorLayout.setVerticalGroup(
            jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_añadirNadadorLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombreNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sp_estatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_estiloNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_distanciaNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sp_recordNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_añadirNadadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sp_medallasNadador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bt_añadirNadador, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Nadador", jp_añadirNadador);

        tb_tablaNadadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Estatura", "Estilo", "Distancia", "Tiempo Record", "Medallas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_tablaNadadores);

        jLabel14.setText("Nadadores");

        bt_listarNadadores.setText("Listar Nadadores");
        bt_listarNadadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_listarNadadoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_listarLayout = new javax.swing.GroupLayout(jp_listar);
        jp_listar.setLayout(jp_listarLayout);
        jp_listarLayout.setHorizontalGroup(
            jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarLayout.createSequentialGroup()
                .addGroup(jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_listarLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(cb_listarNadadoresP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_listarLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bt_listarNadadores)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_listarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(289, 289, 289))
        );
        jp_listarLayout.setVerticalGroup(
            jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addGroup(jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_listarLayout.createSequentialGroup()
                        .addComponent(cb_listarNadadoresP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(bt_listarNadadores)))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Nadadores", jp_listar);

        tb_tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estilo", "Distancia", "Record"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_tablaEventos);

        jLabel15.setText("Eventos");

        bt_refrescarEventos.setText("Refrescar");
        bt_refrescarEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_refrescarEventosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_listarEventosLayout = new javax.swing.GroupLayout(jp_listarEventos);
        jp_listarEventos.setLayout(jp_listarEventosLayout);
        jp_listarEventosLayout.setHorizontalGroup(
            jp_listarEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarEventosLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(jp_listarEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_listarEventosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_listarEventosLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(367, 367, 367))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_listarEventosLayout.createSequentialGroup()
                        .addComponent(bt_refrescarEventos)
                        .addGap(348, 348, 348))))
        );
        jp_listarEventosLayout.setVerticalGroup(
            jp_listarEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarEventosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bt_refrescarEventos)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Eventos", jp_listarEventos);

        jLabel16.setText("Eventos");

        jLabel17.setText("Nadadores");

        bt_añadirNadadorS.setText("Añadir al evento");
        bt_añadirNadadorS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_añadirNadadorSMouseClicked(evt);
            }
        });

        bt_empezarEvento.setText("Empezar Evento");
        bt_empezarEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_empezarEventoMouseClicked(evt);
            }
        });

        bt_elegirEvento.setText("Elegir este evento");
        bt_elegirEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_elegirEventoMouseClicked(evt);
            }
        });

        jLabel18.setText("Nadador 1");

        jLabel19.setText("Nadador 2 ");

        jLabel20.setText("Nadador 3");

        javax.swing.GroupLayout jp_simulacionLayout = new javax.swing.GroupLayout(jp_simulacion);
        jp_simulacion.setLayout(jp_simulacionLayout);
        jp_simulacionLayout.setHorizontalGroup(
            jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_simulacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_empezarEvento)
                .addGap(337, 337, 337))
            .addGroup(jp_simulacionLayout.createSequentialGroup()
                .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_simulacionLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(75, 75, 75)
                        .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pg_piscina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pg_piscina2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pg_piscina3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_simulacionLayout.createSequentialGroup()
                        .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_simulacionLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel16))
                            .addGroup(jp_simulacionLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(cb_eventosSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(123, 123, 123)
                        .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_simulacionLayout.createSequentialGroup()
                                .addComponent(cb_nadadoresSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(bt_añadirNadadorS))
                            .addComponent(jLabel17)))
                    .addGroup(jp_simulacionLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(bt_elegirEvento)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jp_simulacionLayout.setVerticalGroup(
            jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_simulacionLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_eventosSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_nadadoresSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_añadirNadadorS))
                .addGap(18, 18, 18)
                .addComponent(bt_elegirEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_simulacionLayout.createSequentialGroup()
                        .addComponent(bt_empezarEvento)
                        .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_simulacionLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jp_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jp_simulacionLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(48, 48, 48))
                                    .addComponent(jLabel19)))
                            .addGroup(jp_simulacionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pg_piscina1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pg_piscina2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pg_piscina3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(145, 145, 145))
        );

        jTabbedPane1.addTab("Simulacion", jp_simulacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_añadirPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_añadirPaisMouseClicked
        if (tf_nombrePais.getText().equals("") || (int) sp_medallasPais.getModel().getValue() < 0) {
            JOptionPane.showMessageDialog(this, "Tiene que llenar todas las casillas!");
        } else {
            Pais p = new Pais(tf_nombrePais.getText(),
                    (int) sp_medallasPais.getModel().getValue());
            paises.add(p);

            File file = new File("./PaisesParticipantes.UWU");
            FileOutputStream fo = null;
            ObjectOutputStream os = null;

            try {
                fo = new FileOutputStream(file);
                os = new ObjectOutputStream(fo);
                for (Pais paise : paises) {
                    os.writeObject(paise);
                }

                os.flush();
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                fo.close();
                os.close();
            } catch (Exception e) {
            }

            tf_nombrePais.setText("");
            sp_medallasPais.getModel().setValue(0);
            JOptionPane.showMessageDialog(this, "Pais añadido exitosamente!");
            cb_nacionalidad.setModel(refrescarModelo(paises, (DefaultComboBoxModel) cb_nacionalidad.getModel()));
            cb_listarNadadoresP.setModel(refrescarModelo(paises, (DefaultComboBoxModel) cb_listarNadadoresP.getModel()));
        }
    }//GEN-LAST:event_bt_añadirPaisMouseClicked

    private void bt_añadirEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_añadirEventoMouseClicked
        if (cb_distanciaEvento.getSelectedIndex() < 0 || cb_estiloEvento.getSelectedIndex() < 0 || (double) sp_recordEvento.getModel().getValue() == 0) {
            JOptionPane.showMessageDialog(this, "Tiene que llenar las casillas!");
        } else {
            Evento e = new Evento((String) cb_estiloEvento.getSelectedItem(),
                    (String) cb_estiloEvento.getSelectedItem(),
                    (double) sp_recordEvento.getModel().getValue());
            eventos.add(e);

            File file = new File("./Eventos.UWU");
            FileOutputStream fo = null;
            ObjectOutputStream os = null;
            try {
                fo = new FileOutputStream(file);
                os = new ObjectOutputStream(fo);
                for (Evento evento : eventos) {
                    os.writeObject(evento);
                }

                os.flush();
            } catch (Exception e2) {
                e2.printStackTrace();
            }
            try {
                fo.close();
                os.close();
            } catch (Exception e2) {
            }

            cb_distanciaEvento.setSelectedIndex(-1);
            cb_estiloEvento.setSelectedIndex(-1);
            sp_recordEvento.getModel().setValue(0);
            cb_eventosSimulacion.setModel(refrescarModelo(eventos, (DefaultComboBoxModel) cb_eventosSimulacion.getModel()));
            JOptionPane.showMessageDialog(this, "Evento añadido exitosamente!");
        }
    }//GEN-LAST:event_bt_añadirEventoMouseClicked

    private void bt_añadirNadadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_añadirNadadorMouseClicked
        if (tf_nombreNadador.getText().equals("") || cb_nacionalidad.getSelectedIndex() == -1 || cb_estiloNadador.getSelectedIndex() == -1 || cb_distanciaNadador.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Tiene que llenar todas las casillas!");
        } else {
            int cuenta = contarEstilos((Pais) cb_nacionalidad.getSelectedItem(), (String) cb_estiloNadador.getSelectedItem());
            if (cuenta >= 2) {
                JOptionPane.showMessageDialog(this, "No puede agregar mas nadadores de este estilo al pais!");
            } else {
                Nadador n = new Nadador(tf_nombreNadador.getText(),
                        (Pais) cb_nacionalidad.getSelectedItem(),
                        (int) sp_edad.getModel().getValue(),
                        (double) sp_estatura.getModel().getValue(),
                        (String) cb_estiloNadador.getSelectedItem(),
                        (String) cb_distanciaNadador.getSelectedItem(),
                        (double) sp_recordNadador.getModel().getValue(),
                        (int) sp_medallasNadador.getModel().getValue());
                nadadores.add(n);
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_nacionalidad.getModel();
                int indice = cb_nacionalidad.getSelectedIndex();
                ((Pais) modelo.getElementAt(indice)).setNadadores(n);

                File file = new File("./Nadadores.UWU");
                FileOutputStream fo = null;
                ObjectOutputStream os = null;
                try {
                    fo = new FileOutputStream(file);
                    os = new ObjectOutputStream(fo);
                    for (Nadador nadadore : nadadores) {
                        os.writeObject(nadadore);
                    }

                    os.flush();
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
                try {
                    fo.close();
                    os.close();
                } catch (Exception e2) {
                }

                tf_nombreNadador.setText("");
                cb_nacionalidad.setSelectedIndex(-1);
                sp_edad.getModel().setValue(18);
                sp_estatura.getModel().setValue(1);
                cb_distanciaNadador.setSelectedIndex(-1);
                cb_estiloNadador.setSelectedIndex(-1);
                sp_recordNadador.getModel().setValue(1);
                sp_medallasNadador.getModel().setValue(0);
                JOptionPane.showMessageDialog(this, "Nadador añadido exitosamente!");
            }
        }
    }//GEN-LAST:event_bt_añadirNadadorMouseClicked

    private void bt_listarNadadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_listarNadadoresMouseClicked
        if (cb_listarNadadoresP.getSelectedIndex() != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tb_tablaNadadores.getModel();
            while (modelo.getRowCount() > 0) {
                modelo.removeRow(0);
            }
            DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listarNadadoresP.getModel();
            int indice = cb_listarNadadoresP.getSelectedIndex();
            Pais elegido = (Pais) m.getElementAt(indice);

            for (Nadador n : nadadores) {
                Object[] lista = {n.getNombre(),
                    n.getEdad(),
                    n.getEstatura(),
                    n.getEstilo(),
                    n.getDistancia(),
                    n.getRecord(),
                    n.getMedallas()};
                modelo.addRow(lista);
            }
            tb_tablaNadadores.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(this, "Tiene que elegir un pais primero!");
        }
    }//GEN-LAST:event_bt_listarNadadoresMouseClicked

    private void bt_elegirEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_elegirEventoMouseClicked
        if (cb_eventosSimulacion.getSelectedIndex() != -1) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_nadadoresSimulacion.getModel();
            modelo.removeAllElements();
            for (Nadador n : nadadores) {
                if (n.getEstilo().equals(((Evento) cb_eventosSimulacion.getSelectedItem()).getEstilo())
                        || n.getDistancia().equals(((Evento) cb_eventosSimulacion.getSelectedItem()).getDistancia())) {
                    modelo.addElement(n);
                }
            }
            cb_nadadoresSimulacion.setModel(modelo);
        }
    }//GEN-LAST:event_bt_elegirEventoMouseClicked

    private void bt_añadirNadadorSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_añadirNadadorSMouseClicked
        if (competidores.size() != 3 && cb_nadadoresSimulacion.getSelectedIndex() != -1) {
            competidores.add((Nadador) cb_nadadoresSimulacion.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Nadador Añadido");
        }
    }//GEN-LAST:event_bt_añadirNadadorSMouseClicked

    private void bt_empezarEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_empezarEventoMouseClicked
        if (competidores.size() >= 2) {
            ArrayList<JProgressBar> barras = new ArrayList();
            barras.add(pg_piscina1);
            barras.add(pg_piscina2);
            barras.add(pg_piscina3);

            Simulacion simu = new Simulacion(competidores, barras);
            simu.start();

        } else {
            JOptionPane.showMessageDialog(this, "Tiene que elegir los competidores");
        }
    }//GEN-LAST:event_bt_empezarEventoMouseClicked

    private void bt_refrescarEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_refrescarEventosMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tb_tablaEventos.getModel();
        int cc = 0;
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(cc);
        }

        for (Evento evento : eventos) {
            Object[] ob = {evento.getEstilo(),
                evento.getDistancia(),
                evento.getRecord()};
            modelo.addRow(ob);
        }
        tb_tablaEventos.setModel(modelo);
    }//GEN-LAST:event_bt_refrescarEventosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public static int contarEstilos(Pais p, String estilo) {
        int cc = 0;
        for (Nadador nadador : p.getNadadores()) {
            if (nadador.getEstilo() == estilo) {
                cc++;
            }
        }
        return cc;
    }

    public static DefaultComboBoxModel refrescarModelo(ArrayList lista, DefaultComboBoxModel modelo) {
        modelo.removeAllElements();
        for (Object object : lista) {
            modelo.addElement(object);
        }
        return modelo;
    }

    ArrayList<Pais> paises = new ArrayList();
    ArrayList<Nadador> nadadores = new ArrayList();
    ArrayList<Evento> eventos = new ArrayList();
    ArrayList<Nadador> competidores = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_añadirEvento;
    private javax.swing.JButton bt_añadirNadador;
    private javax.swing.JButton bt_añadirNadadorS;
    private javax.swing.JButton bt_añadirPais;
    private javax.swing.JButton bt_elegirEvento;
    private javax.swing.JButton bt_empezarEvento;
    private javax.swing.JButton bt_listarNadadores;
    private javax.swing.JButton bt_refrescarEventos;
    private javax.swing.JComboBox<String> cb_distanciaEvento;
    private javax.swing.JComboBox<String> cb_distanciaNadador;
    private javax.swing.JComboBox<String> cb_estiloEvento;
    private javax.swing.JComboBox<String> cb_estiloNadador;
    private javax.swing.JComboBox<String> cb_eventosSimulacion;
    private javax.swing.JComboBox<String> cb_listarNadadoresP;
    private javax.swing.JComboBox<String> cb_nacionalidad;
    private javax.swing.JComboBox<String> cb_nadadoresSimulacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jp_añadirEvento;
    private javax.swing.JPanel jp_añadirNadador;
    private javax.swing.JPanel jp_añadirPais;
    private javax.swing.JPanel jp_listar;
    private javax.swing.JPanel jp_listarEventos;
    private javax.swing.JPanel jp_simulacion;
    private javax.swing.JProgressBar pg_piscina1;
    private javax.swing.JProgressBar pg_piscina2;
    private javax.swing.JProgressBar pg_piscina3;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_estatura;
    private javax.swing.JSpinner sp_medallasNadador;
    private javax.swing.JSpinner sp_medallasPais;
    private javax.swing.JSpinner sp_recordEvento;
    private javax.swing.JSpinner sp_recordNadador;
    private javax.swing.JTable tb_tablaEventos;
    private javax.swing.JTable tb_tablaNadadores;
    private javax.swing.JTextField tf_nombreNadador;
    private javax.swing.JTextField tf_nombrePais;
    // End of variables declaration//GEN-END:variables
}
